import { useState } from 'react'
import { CheckCircle2, XCircle, AlertTriangle } from 'lucide-react'
import type { FaithfulnessSentence, EvidenceItem } from '@/types'
import { cn } from '@/lib/utils'

const statusConfig = {
  verified: { icon: CheckCircle2, className: 'bg-verdict-support/10 text-verdict-support border-verdict-support/25', label: 'Verified' },
  unsupported: { icon: AlertTriangle, className: 'bg-verdict-warn/10 text-verdict-warn border-verdict-warn/25', label: 'Unsupported' },
  contradiction: { icon: XCircle, className: 'bg-verdict-contradict/10 text-verdict-contradict border-verdict-contradict/25', label: 'Contradiction' },
} as const

export function FaithfulnessView({
  sentences,
  evidence,
}: {
  sentences: FaithfulnessSentence[]
  evidence: EvidenceItem[]
}) {
  const [activeId, setActiveId] = useState<string | null>(null)
  const findEvidence = (id: string) => evidence.find((e) => e.id === id)
  const active = sentences.find((s) => s.id === activeId)

  return (
    <div className="grid gap-6 lg:grid-cols-[1.4fr_1fr]">
      <div className="space-y-3">
        {sentences.map((s) => {
          const cfg = statusConfig[s.status]
          const Icon = cfg.icon
          const isActive = activeId === s.id
          return (
            <button
              key={s.id}
              onClick={() => setActiveId(isActive ? null : s.id)}
              className={cn(
                'w-full rounded-xl border p-4 text-left transition-all',
                isActive ? 'border-clinical-400 ring-2 ring-clinical-400/25' : 'border-mist-200 hover:border-mist-300',
                'bg-white'
              )}
            >
              <div className="flex items-start gap-3">
                <Icon className={cn('mt-0.5 h-4 w-4 flex-none', cfg.className.split(' ')[1])} />
                <div className="min-w-0 flex-1">
                  <p className="text-sm leading-relaxed text-ink-800">{s.text}</p>
                  <div className="mt-2 flex flex-wrap items-center gap-2">
                    <span className={cn('inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-xs font-medium', cfg.className)}>
                      {cfg.label}
                    </span>
                    <span className="mono-label">confidence {s.confidence}%</span>
                    {s.evidenceIds.length > 0 && (
                      <span className="mono-label text-clinical-600">
                        {s.evidenceIds.length} linked source{s.evidenceIds.length > 1 ? 's' : ''}
                      </span>
                    )}
                  </div>
                </div>
              </div>
            </button>
          )
        })}
      </div>

      <div className="lg:sticky lg:top-24 lg:self-start">
        <div className="rounded-xl border border-mist-200 bg-mist-50 p-5">
          <p className="mono-label mb-3">Evidence mapping</p>
          {!active && (
            <p className="text-sm text-ink-500">
              Select a sentence to see exactly which retrieved evidence supports or fails to support it.
            </p>
          )}
          {active && active.evidenceIds.length === 0 && (
            <div className="rounded-lg border border-verdict-warn/25 bg-verdict-warn/5 p-3 text-sm text-ink-700">
              No retrieved evidence maps to this sentence — that's why it's flagged. It was generated by the
              LLM but did not pass the entailment check against the evidence corpus.
            </div>
          )}
          {active &&
            active.evidenceIds.map((id) => {
              const ev = findEvidence(id)
              if (!ev) return null
              return (
                <div key={id} className="mb-3 rounded-lg border border-mist-200 bg-white p-3 last:mb-0">
                  <p className="text-xs font-semibold text-ink-900">{ev.title}</p>
                  <p className="mt-1 text-xs text-ink-500">
                    {ev.source} · {ev.year} · reliability {ev.reliabilityScore}
                  </p>
                </div>
              )
            })}
        </div>
      </div>
    </div>
  )
}
