import { useParams, Link } from 'react-router-dom'
import { Printer, Share2, Copy, ArrowLeft } from 'lucide-react'
import { Eyebrow, Card, Badge, Button } from '@/components/ui/Primitives'
import { CredibilityGauge, MiniMeter } from '@/components/credibility/CredibilityGauge'
import { ConsensusTimeline } from '@/components/consensus/ConsensusChart'
import { FaithfulnessView } from '@/components/faithfulness/FaithfulnessView'
import { EvidenceCard } from '@/components/evidence/EvidenceCard'
import { useAppStore } from '@/store/useAppStore'
import { formatDate, verdictTone } from '@/lib/utils'

export default function ReportPage() {
  const { id } = useParams()
  const history = useAppStore((s) => s.history)
  const record = history.find((v) => v.id === id) ?? history[0]
  const tone = verdictTone(record.verdict)

  return (
    <div className="mx-auto max-w-5xl space-y-8 pb-16">
      <div className="flex items-center justify-between">
        <Link to="/app/history" className="flex items-center gap-1.5 text-sm font-medium text-ink-600 hover:text-ink-900">
          <ArrowLeft className="h-4 w-4" /> Back to history
        </Link>
        <div className="flex gap-2">
          <Button variant="secondary" onClick={() => window.print()}><Printer className="h-4 w-4" /> Export PDF</Button>
          <Button variant="secondary"><Copy className="h-4 w-4" /> Copy citation</Button>
          <Button variant="secondary"><Share2 className="h-4 w-4" /> Share</Button>
        </div>
      </div>

      <Card className="p-8">
        <div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <Eyebrow className="text-clinical-600">Verification report</Eyebrow>
            <h1 className="mt-2 text-2xl font-semibold leading-snug tracking-tight text-ink-950">{record.claim}</h1>
            <div className="mt-3 flex flex-wrap items-center gap-2">
              <Badge tone="clinical">{record.disease}</Badge>
              <span className="text-xs text-ink-500">Verified {formatDate(record.submittedAt)}</span>
              <span className="font-mono text-xs text-ink-400">{record.modelVersion}</span>
            </div>
          </div>
          <CredibilityGauge score={record.credibility.overall} />
        </div>

        <div className="mt-8 grid gap-4 rounded-xl bg-mist-50 p-5 sm:grid-cols-2 lg:grid-cols-4">
          <MiniMeter label="Evidence confidence" value={record.credibility.evidenceConfidence} />
          <MiniMeter label="Consensus confidence" value={record.credibility.consensusConfidence} />
          <MiniMeter label="Source quality" value={record.credibility.sourceQuality} />
          <MiniMeter label="Faithfulness confidence" value={record.credibility.faithfulnessConfidence} />
        </div>

        <div className={`mt-6 rounded-xl p-4 ${tone.bg}`}>
          <p className="mono-label mb-1">Final verdict</p>
          <p className={`text-xl font-semibold ${tone.text}`}>{record.verdict}</p>
        </div>
      </Card>

      <Card className="p-6">
        <p className="mb-4 text-sm font-semibold text-ink-950">Explanation &amp; faithfulness verification</p>
        <FaithfulnessView sentences={record.explanation} evidence={record.evidence} />
        <p className="mt-6 rounded-lg border border-mist-200 bg-mist-50 p-3 text-xs leading-relaxed text-ink-500">
          This explanation is generated by an AI model and independently checked against retrieved
          evidence. It is provided for research and literacy purposes and is not a substitute for
          professional medical advice.
        </p>
      </Card>

      <Card className="p-6">
        <p className="mb-1 text-sm font-semibold text-ink-950">Scientific consensus timeline</p>
        <p className="mb-4 text-xs text-ink-500">Supporting, contradicting, and neutral studies by year</p>
        <ConsensusTimeline data={record.consensusTimeline} />
      </Card>

      <div>
        <p className="mb-4 text-sm font-semibold text-ink-950">References ({record.evidence.length})</p>
        <div className="grid gap-4 lg:grid-cols-2">
          {record.evidence.map((e) => (
            <EvidenceCard key={e.id} evidence={e} />
          ))}
        </div>
      </div>
    </div>
  )
}
